# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\" \n\x0cHelloRequest\x12\x10\n\x08language\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"I\n\x12HelloStreamRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x12\n\nintervalMS\x18\x03 \x01(\x05\"4\n\x13HelloStreamResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t2\xac\x01\n\x11HelloWorldService\x12?\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x19.helloworld.HelloResponse\x12V\n\x11SayHelloManyTimes\x12\x1e.helloworld.HelloStreamRequest\x1a\x1f.helloworld.HelloStreamResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=32
  _globals['_HELLOREQUEST']._serialized_end=64
  _globals['_HELLORESPONSE']._serialized_start=66
  _globals['_HELLORESPONSE']._serialized_end=98
  _globals['_HELLOSTREAMREQUEST']._serialized_start=100
  _globals['_HELLOSTREAMREQUEST']._serialized_end=173
  _globals['_HELLOSTREAMRESPONSE']._serialized_start=175
  _globals['_HELLOSTREAMRESPONSE']._serialized_end=227
  _globals['_HELLOWORLDSERVICE']._serialized_start=230
  _globals['_HELLOWORLDSERVICE']._serialized_end=402
# @@protoc_insertion_point(module_scope)
